feat：添加获取地址参数方法及单元测试用例 idinofe#32
idinofe/xt-core pull request #39
Opened 2023-08-15 08:48 UTC by meihuihui

2023-08-15 09:19 UTC, JohnieXu requested changes
需要修改一下

2023-08-15 09:19 UTC, JohnieXu commented on src/common.test.ts
> +describe('getQuery', () => {
需要补充更多测试场景
- 2个参数同时存在
- 2个参数之一不存在
- 2个参数同时不存在
- 2个参数分别未按照类型传递
- 第1个参数正常，第二个参数不存在或者是第1个参数对象上不存在的key

2023-08-15 09:19 UTC, JohnieXu commented on src/common.ts
> +  const obj = {} as NObject
可以优化为，如果不存在 `number` 类型可以去掉（需要看 getQuery 是否会对类型进行转换）
```suggestion
  const obj = {} as Record<string, string | number | undefined>
```

2023-08-15 09:19 UTC, JohnieXu commented on src/common.ts
> +  // 获取url中参数值
需要说明一下此方法与 `query-string` `qs` 等库的区别，是否会进行 `decodeURI` 等

2023-08-15 09:19 UTC, JohnieXu commented on src/common.ts
> +  // return (obj as any)[a]
无用代码可以去掉
```suggestion
```

2023-08-15 09:19 UTC, JohnieXu commented on src/common.ts
> +  // return obj[a as keyof typeof obj]
无用代码可以去掉
```suggestion
```

2023-08-16 03:08 UTC, JohnieXu approved these changes

2023-08-16 03:16 UTC, EleanorZcy commented on src/common.ts
> +  }
格式问题
```suggestion
}
```

2023-08-16 07:21 UTC, closed without merging